### ISSUE TITLE
Lein 2.8.2 warns about deprecated hook lein-environ.plugin/hooks

### ISSUE THREAD

**Issue by a613** [weavejester/environ#88]
After upgrading from lein 2.8.1 to 2.8.2:

```
$ lein --version
Warning: implicit hook found: lein-environ.plugin/hooks
Hooks are deprecated and will be removed in a future version.
Leiningen 2.8.2 on Java 1.8.0_151 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by extremus** [comment]
I had the same warning with Leiningen 2.8.3 on Java 10.0.2. I've changed the [:plugin](https://github.com/technomancy/leiningen/blob/master/doc/PLUGINS.md#requiring-plugins) section to `[ lein-environ "1.1.0" :hooks false ]` and it's now ok in my project.

**Comment by a613** [comment]
That causes the following crash:

```
Exception in thread "main" java.lang.AssertionError: Assert failed: transport-fn, compiling:(/private/var/folders/3q/4g1b3jvs1wq9ndlrkrzp7dv80000gn/T/form-init3668445742910249714.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.AssertionError: Assert failed: transport-fn
	at nrepl.core$connect.invokeStatic(core.clj:168)
	at nrepl.core$connect.doInvoke(core.clj:168)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at nrepl.ack$send_ack.invokeStatic(ack.clj:45)
	at nrepl.ack$send_ack.invoke(ack.clj:41)
	at nrepl.server$start_server.invokeStatic(server.clj:146)
	at nrepl.server$start_server.doInvoke(server.clj:105)
	at clojure.lang.RestFn.invoke(RestFn.java:1096)
	at user$eval38553.invokeStatic(form-init3668445742910249714.clj:1)
	at user$eval38553.invoke(form-init3668445742910249714.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
```

**Comment by a613** [comment]
@extremus thanks, that works fine in my case too.

**Comment by terjedahl** [comment]
Yes, adding `:hooks false` does get rid of the warning, but doesn't it also then disable writing `:env` values in _project.clj_ and _profiles.clj_ from being written to _.lein-env_; thereby disabling the most useful feature of the plugin?
Can the plugin be re-written in such a way that it no longer relies on hooks?

**Comment by darwin** [comment]
@terjedahl is correct. Disabling hooks will stop writing `.lein-env`. It seems to work just because the old file stays in place until you start from scratch (e.g. clone the repo somewhere else).

The whole idea of writing to a file which is then consumed by the library is quite brittle. For example I had a lot of headaches when using this with lein-shell plugin. Imagine running a shell script from leiningen which then happens to call some other lein command (you end up with nested lein processes). This way only inner-most process wins writing the file and others get wrong environments depending on who was last writer to the file when they happen to read it.

You have to understand implementation details of this plugin to see what went wrong. I would recommend opening a PR in leiningen itself and implement independent support for ENV variables there. Dynamic `.lein-env` is not a good idea.

**Comment by weavejester** [comment]
If anyone can come up with a better implementation for passing the environment data from the Leiningen project to the application process, I'd welcome a PR.

**Comment by terjedahl** [comment]
One workaround could be to replace the hook-mechanism with a middleware mechanism.  
I understand that this would be conceptually wrong, as middleware shouldn't have side-effects.  We wouldn't be actually be altering the project-structure either.  And also, as implicit middleware is going away, the user would still have to declare it explicitly as `:middleware`.

Another solution might be to simply have it hook in via the `:prep-tasks` mechanism.  This could possibly even alleviate @darwin 's issue as it could be added selectively in profiles.

**Comment by terjedahl** [comment]
I was thinking along similar lines as you @wesleyhall: As `environ.core/env` is a result of calling `environ.core/read-env`, which in turn amongst other reads from file '.lein-env', why not skip the intermediate step of generating the '.lein-env' file and instead read directly from the 'project.clj'.  The challenge might be in detecting/applying profiles, though ...  :-/

**Comment by wesleyhall** [comment]
@terjedahl 

I did take a very quick look into this last night and Bruce @ Figwheel actually has this little project: 

https://github.com/bhauman/simple-lein-profile-merge

He doesn't seem particularly enthusiastic about it being ready for wider adoption, but it is out there.

**Comment by kengruven** [comment]
I just spent a couple days learning way more than I ever wanted to about lein and environ, because I thought I was helping myself by silencing the "Warning: implicit hook found" message.  Oops.

In the short term, how do you feel about a note in the README that warns idiots like me not to use `:hooks false` in their project.clj, even if they see red warnings in their logs?

**Comment by radhikalism** [comment]
There seems to be two issues under discussion here. One is about avoiding the Leiningen implicit hooks warning (but keeping the brittle `.lein-env` file strategy). The other is about finding a different way to communicate project maps to the project runtime.

On the first question of implicit hooks alone:

* Is there any reason lein-environ cannot use `:prep-tasks` to explicitly generate its `.lein-env` file as a task, rather than hooks?
* Or, is there any reason lein-environ cannot use an explicit hook instead of an implicit hook, at least, to avoid this warning?

**Comment by rome-user** [comment]
> is there any reason lein-environ cannot use an explicit hook instead of an implicit hook, at least, to avoid this warning?

Hooks in general are scheduled to be removed in a future release of Leiningen. Anything that keeps using hooks is NG. This leaves us with the `:prep-tasks` question. I assume the problem with prep task is the inability of plugins to add their own prep task. The user may have to configure it manually.
